[package]
name = "labrynth-pub-game"
version = "0.1.0"
authors = ["Adam Shaw <discourse@gmail.com>"]
edition = "2018"

[dependencies]
bevy = "0.1.2"
log = { version = "0.4.8", features = ["serde"] }

[features]
